xyz: 
  zhudengkui: 
    zookeeper: 127.0.0.1:2181
    
thread:
  pool:
    corePoolSize: 5
    maxPoolSize: 20
    queueCapacity: 200
    keepAliveSeconds: 60
    threadNamePrefix: ASYNC_

dubbo:
  application:
    name: user-service-consumer
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry