server:
  port: 8080
  servlet:
    context-path: /hello


spring:
  profiles:
    include: sharding-prod

mybatis-plus:
  mapper-locations: classpath*:config/**/mapper/*.xml
  type-handlers-package: com.zdk.hello.handler

logging:
  level: 
    com: debug