server:
  port: 8080
  servlet:
    context-path: /hello

spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Mysql@1111

  redis:
    host: 127.0.0.1
    port: 6379
    password: Zdk@2020
    database: 0
